### ISSUE TITLE
Final organization of the repository

### ISSUE THREAD

**Issue by iuryt** [oceanhackweek/ohw21-proj-model-subsampling#10]
I was thinking about the folder structure of the repository and would like to know your opinion.

- `py` - .py, .ipynb files.
- `data` - data we keep in the repository or data we temporarily download
- `img` - for pushing figures we want to keep on github

I was also thinking if it would be a good idea to kind of standardize the name of the files, putting some number in the beginning that explain the order we should run.

- 00-download_LLC
- 01-interpolation
- 02-visualization

Or something like this.
What is your opinion?

**Comment by kdrushka** [comment]
> 
    py - .py, .ipynb files.
    data - data we keep in the repository or data we temporarily download
    img - for pushing figures we want to keep on github

I like this plan 

> 
    00-download_LLC
    01-interpolation
    02-visualization

Do you mean for all the code snippets that go into the final project notebook? Or are you proposing that we run three separate notebooks? (I think it makes more sense to have a single final notebook - but I'm totally open to discussion!)

**Comment by iuryt** [comment]
I see.. so now it it not structured because we are still building blocks. 

So the final notebook will

1. Check if there are all files there
2. Download it, if not
3. Load files to memory
4. Load glider data or create a fake one
5. Interpolate
6. Create figures

right?

**Comment by kdrushka** [comment]
That's my understanding - seems like that would be the most useful for sharing and adapting in the future. 

> Load glider data or create a fake one
Perhaps some sort of flag to make this choice , e.g. 
`TRAJECTORY_TYPE='simulated' or 'glider'` , followed by an `if` statement? (note sure if that's good practice, but it's how I code :)  )

**Comment by kdrushka** [comment]
Thanks @dianalg for starting FinalProjectSummary.ipynb ! Some tasks for final organization:

- [x] load multiple files (implementing @iuryt 's updates to the PreSWOT notebook)
- [x] add flag to select trajectory - realistic glider, simulated glider, simulated uctd
- [ ] add visualizations
