### ISSUE TITLE
Script to load multiple model data files 

### ISSUE THREAD

**Issue by kdrushka** [oceanhackweek/ohw21-proj-model-subsampling#2]
- download model output files - [California Current ROMS](https://data.cencoos.org/#search?type_group=all&query=ROMS&page=1) and/or [llc4320 mitgcm](https://podaac.jpl.nasa.gov/datasetlist?ids=Processing+Levels&values=4+-+Gridded+Model+Output&search=Pre-SWOT+llc4320&view=list&provider=)

- [x]  load multiple files into an xarray dataset
- [ ]  ensure the variables/dimensions have a sensible naming structure, so that we can run the subsampling on different simulation data - @kdrushka to share code for making llc4320 names => *not necessary*

**Comment by iuryt** [comment]
Not sure I understand what we need to do for the second task, but the first one I just merged to main.

**Comment by kdrushka** [comment]
Great! I think the second task isn't necessary since we are only using one simulation. I will remove it & close the issue.
