### ISSUE TITLE
Script to apply interpolation of the model data onto the survey trajectory and save/plot output

### ISSUE THREAD

**Issue by kdrushka** [oceanhackweek/ohw21-proj-model-subsampling#4]
* @iuryt has done this for the 2-d example case, but it may be more complex for 4-D data/ interpolation
* optimize with Dask or parallel computing tools?

**Comment by iuryt** [comment]
I can work on that, if you haven't done yet.

- [x] Test for lon (points), lat (points), z (points) and time (points)
- [ ] Test for structured data (CTD casts?)
- [ ] Test with and without dask chunks and check optimization

**Comment by kdrushka** [comment]
Great!

**Comment by kdrushka** [comment]
Other tasks to do:

- [x] interpolate in time (dependent on loading multiple files if time is >1 day)
- [x] interpolate other variables (e.g., salt, velocity => requires shifting the grid slightly - @dhruvbalwada to do)

**Comment by dhruvbalwada** [comment]
I added code to show how to change grids for U, V or calculate the vorticity in the notebook: Application2LLC.ipynb
