### ISSUE TITLE
Transpose glider data

### ISSUE THREAD

**Issue by dhruvbalwada** [oceanhackweek/ohw21-proj-model-subsampling#6]
The glider data lives here: https://github.com/earthcube2021/ec21_balwada_etal 
If you look through the notebook, you should be able to see how to read the data (in the initial part of the notebook).

There are two gliders. 

Please let me know if you have any questions.

**Comment by dianalg** [comment]
Ok, I have an xarray dataset with the transposed coordinates. @iuryt, what format do you need a trajectory to be in for interpolation? @dhruvbalwada mentioned that llc4320 does not have lat, lon coordinates. I'm having trouble downloading the model data, and am not sure what to do about this?

Also, is it a problem that depth is still represented as pressure in the dataset?

**Comment by dhruvbalwada** [comment]
It is ok that the depth is in pressure, for practical purposes pressure == depth.

**Comment by dhruvbalwada** [comment]
What error do you get when trying to download model data?

**Comment by dianalg** [comment]
It's all sorted. Not sure what to do about the coordinate mismatch though.

**Comment by dhruvbalwada** [comment]
What do you mean by coordinate mismatch?

**Comment by dianalg** [comment]
The fact that the model data doesn't seem to have lat, lon?

**Comment by dhruvbalwada** [comment]
Ah ok, I solved that issue in the notebook: https://github.com/oceanhackweek/ohw21-proj-model-subsampling/blob/main/Application2LLC.ipynb 
I first convert from the lat-lon to the model's index representation, and then use that.
